name: ci

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF##*/}
            echo ::set-output name=tag_name::${TAG}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login do docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build and publish image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cathive/concourse-sonarqube-resource:${{ steps.prepare.outputs.tag_name }}
            cathive/concourse-sonarqube-resource:latest
